### ISSUE TITLE
[BUG] Full migration fails when importing the config from source BIG-IP 6900S v11.6.3

### ISSUE THREAD

**Issue by martino76** [f5devcentral/f5-journeys#43]
**Describe the bug**
Full migration fails when importing the config from source BIG-IP 6900S v11.6.3

**To Reproduce**
In a full migration from a physical BIG-IP 6900S running v11.6.3 to a VE running the same version I receive the following error. I am not able to import the config from the source BIG-IP using F5 journeys

```
Configuration loading failed
value too long for type character varying(5)
```

log error:

```INFO 2022-03-23 07:18:58,491 sftp [chan 5] Opened sftp connection (server version 3)
DEBUG 2022-03-23 07:18:58,491 sftp [chan 5] stat(b'/var/local/ucs/CEN-LB1l-20220323-071848.ucs')
DEBUG 2022-03-23 07:18:58,493 sftp [chan 5] stat(b'/var/local/ucs/CEN-LB1-20220323-071848.ucs')
DEBUG 2022-03-23 07:18:58,494 sftp [chan 5] open(b'/var/local/ucs/CEN-LB1-20220323-071848.ucs', 'rb')
DEBUG 2022-03-23 07:18:58,496 sftp [chan 5] open(b'/var/local/ucs/CEN-LB1-20220323-071848.ucs', 'rb') -> 00000000
DEBUG 2022-03-23 07:18:58,793 sftp [chan 5] close(00000000)
DEBUG 2022-03-23 07:18:58,795 channel [chan 6] Max packet in: 32768 bytes
DEBUG 2022-03-23 07:18:58,795 channel [chan 6] Max packet out: 32768 bytes
DEBUG 2022-03-23 07:18:58,796 transport Secsh channel 6 opened.
DEBUG 2022-03-23 07:18:58,797 channel [chan 6] Sesch channel 6 request ok
DEBUG 2022-03-23 07:18:58,798 channel [chan 6] EOF sent (6)
DEBUG 2022-03-23 07:18:58,807 channel [chan 6] EOF received (6)
ERROR 2022-03-23 07:19:00,115 handlers Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(5)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/journeys/backend/views.py", line 399, in source
    controller.initialize(
  File "/code/journeys/controller.py", line 171, in initialize
    self._reformat_input()
  File "/code/journeys/utils/perf.py", line 18, in wrap
    return f(*args, **kw)
  File "/code/journeys/controller.py", line 229, in _reformat_input
    self.read_config()
  File "/code/journeys/utils/perf.py", line 18, in wrap
    return f(*args, **kw)
  File "/code/journeys/controller.py", line 260, in read_config
    source_device.save()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(5)


ERROR 2022-03-23 07:19:00,116 log Internal Server Error: /sessions/1/source
```
**Expected behavior**
Configuration load

**Context**

- Please specify, app version:
  Journeys Release 3.3.0

- And Platform version of the system you want to migrate.
  attempting to migrate BIG-IP 6900S v11.6.3  to BIG-IP VE running the same version on the physical platform i5800

**Comment by zahajkiewicz** [comment]
@martino76 could you please create an SR ticket and upload the problematic UCS file for us to investigate? https://www.f5.com/services/support

**Comment by jszczepanskif5** [comment]
Looks like an error trying to retrieve F5 platform ID from the UCS. Usually this follows the format of a letter followed by three numbers, which for the i5800 platform should be C119, but somehow this seems to be different here, and I cannot reproduce the issue right now.

An SR ticket uploading the UCS might not be necessary - could you first paste in here contents of the `/PLATFORM` file on your source device? It should look somewhat like this:
```
platform=C119
family=0xF8000000
host=C119
systype=0x9c
```

If the platform value looks nothing out of the ordinary, I'd also ask you to list us the contents of the platform file within the UCS, should have the same format as above:
```
tar -axf YOUR_UCS.ucs config/.ucs_platform -O
```

**Comment by martino76** [comment]
> @martino76 could you please create an SR ticket and upload the problematic UCS file for us to investigate? https://www.f5.com/services/support

I did already this is the SR C3780962.

```
platform=Gemini
family=0xA0000000
host=Gemini
systype=0x6c
```

**Comment by martino76** [comment]
I have uploaded ucs file to the case C3780962.

**Comment by martino76** [comment]
I solve the issue by changing the platform name.
